// Filming defaults captured from the approved control-panel setup.
export const DEFAULT_UI = {
  currentOn: true,
  showIndicator: true,
  showCurrentPulses: false,
  showCurrentComets: true,
  showCurrentCometHeads: true,
  showCurrentArrows: false,
  showFieldLines: true,
  showFieldPulses: false,
  showFieldComets: true,
  showFieldCometHeads: true,
  showFieldArrows: false,
  currentIndicatorColor: '#ffc875',
  currentArrowColor: '#ffc875',
  fieldLineColor: '#ffffff',
  fieldMotionColor: '#ffffff',
  fieldArrowColor: '#ffffff',
  currentIndicatorStrength: 0.60,
  currentPulseSpeed: 1.00,
  currentPulseSpacing: 140,
  currentPulseWidth: 0.155,
  currentCometTail: 3.0,
  currentCometHeadSize: 0.80,
  currentTrackWidth: 12,
  currentPathOffsetX: 0,
  currentPathOffsetY: 0,
  currentArrowSpacing: 340,
  currentArrowSize: 1.0,
  currentArrowStrength: 0.75,
  fieldLineStrength: 3.00,
  fieldLineOpacity: 0.32,   // absolute line opacity; 1 = fully bright
  fieldMaxRadiusPx: 1450,
  fieldFirstRadiusPx: 67,
  fieldRadiusMultiplier: 1.47,
  fieldFalloffCurve: 1.00,
  fieldLineCount: 12,
  fieldLineThickness: 2.20,
  fieldLineDetail: 88,
  fieldMotionStrength: 1.25,
  fieldMotionSpeed: 1.00,
  fieldMotionSpacing: 170,
  fieldPulseWidth: 0.080,
  fieldCometTail: 3.0,
  fieldCometHeadSize: 0.75,
  fieldMotionThickness: 0.75,
  fieldArrowDensity: 1.00,
  fieldArrowSize: 1.00,
  fieldArrowStrength: 1.20,
  fieldArrowSpeed: 0,
  clipToCardboard: true,
  calibrationMode: false,
  renderStyle: 'line',
  filingVisibility: 1.20,
  filingThickness: 1.10,
  previewStride: 1,
  previewShadows: false,
  liftScale: 2.00,
  tapVibration: true,
  boardShake: 0.90,
  // Compass prop (straight-wire stage): position in plane meters (null =
  // auto-place beside the wire on load), body diameter in meters, and how
  // strongly the wire field reads against Earth's (needle sensitivity).
  showCompass: true,
  compassX: null,
  compassY: null,
  compassSize: 0.056,
  compassSensitivity: 3.0,
  compassOrbitDur: 8,   // seconds for one full revolution around the wire
  // When true, field-motion comets start hidden and only appear on the arc
  // the compass has swept during '☉ Trace rings one by one'.
  fieldRevealMode: false,
  recFormat: 'mp4',
  recFps: 24,
  recQuality: 'ultra',
  recSize: '2k',
  logLive: false,
};
