import { DEFAULT_UI } from './defaults.js';

// Preset takes. Each is { name, hint, duration, params?, timeline }.
// Timelines use the un-expanded event grammar from sim/timeline.js.

export const PRESETS = [
  {
    name: 'Manual stage',
    hint: 'Starts from the saved filming setup: current on, dense sprinkle, tap when you want the reveal.',
    duration: 20,
    ui: { ...DEFAULT_UI },
    cal: { holeWallR: 0.0115 },
    params: {
      currentA: 30,
      currentMode: 'dc',
      acFreq: 5,
      rampDur: 0.4,
      currentDir: 1,
      currentAutoAlign: false,
      currentMotion: 0.50,
      fieldReach30A: 0.080,
      fieldFalloffPower: 1.15,
      chainSpacing: 0.003,
      chainStrength: 0.30,
      inwardPull: 0.00325,
      visualFriction: 0.25,
      slideAmount: 1.00,
      alignSpeed: 4.0,
      rotateSpeed: 5.25,
      tapStrength: 8.0,
      tapLiftAll: 1.0,
      tapJitterAmount: 0.28,
      filingMedianL: 0.70e-3,
      sprinkleCount: 18000,
      strayCount: 2401,
      sprinkleR: 0.190,
      sprinklePattern: 'sheet',
      sprinkleClump: 0.65,
    },
    timeline: [
      { t: 0.2, type: 'sprinkle', count: 18000, strayCount: 2401, pattern: 'sheet', radius: 0.190, clump: 0.65 },
    ],
  },
  {
    name: 'Classic reveal',
    hint: 'Sprinkle → current on → taps → cheated field arcs bloom outward from the wire.',
    duration: 9,
    params: { currentA: 30, currentMode: 'dc' },
    timeline: [
      { t: 0.2, type: 'sprinkle', count: 14000, strayCount: 3000, pattern: 'sheet', radius: 0.17, clump: 0.01 },
      { t: 2.0, type: 'current', on: true, amp: 30, mode: 'dc', rampDur: 0.5 },
      { t: 3.0, type: 'tap', strength: 8 },
      { t: 3.6, type: 'tap', strength: 8 },
      { t: 4.2, type: 'tap', strength: 9 },
      { t: 5.0, type: 'tap', strength: 7 },
      { t: 5.8, type: 'tap', strength: 6 },
    ],
  },
  {
    name: 'High current bloom',
    hint: '80 A — the aligned region expands quickly after taps.',
    duration: 9,
    params: { currentA: 80, currentMode: 'dc' },
    timeline: [
      { t: 0.2, type: 'sprinkle', count: 15000, strayCount: 3000, pattern: 'sheet', radius: 0.18, clump: 0.01 },
      { t: 1.8, type: 'current', on: true, amp: 80, mode: 'dc', rampDur: 0.6 },
      { t: 2.8, type: 'tapBurst', n: 5, interval: 0.55, strength: 9 },
      { t: 6.2, type: 'tap', strength: 5 },
    ],
  },
  {
    name: 'Tap vs no tap',
    hint: 'Current on for 3 s — it waits. Then taps reveal the field.',
    duration: 12,
    params: { currentA: 30, currentMode: 'dc' },
    timeline: [
      { t: 0.2, type: 'sprinkle', count: 14000, strayCount: 3000, pattern: 'sheet', radius: 0.17, clump: 0.01 },
      { t: 1.5, type: 'current', on: true, amp: 30, mode: 'dc', rampDur: 0.4 },
      { t: 6.0, type: 'tapBurst', n: 6, interval: 0.6, strength: 8 },
    ],
  },
  {
    name: 'AC shimmer',
    hint: '8 Hz AC — filings near the wire shimmer without settling far away.',
    duration: 10,
    params: { currentA: 45, currentMode: 'ac', acFreq: 8 },
    timeline: [
      { t: 0.2, type: 'sprinkle', count: 14000, strayCount: 3000, pattern: 'sheet', radius: 0.17, clump: 0.01 },
      { t: 1.5, type: 'current', on: true, amp: 45, mode: 'ac', freq: 8, rampDur: 0.8 },
      { t: 3.0, type: 'autoTap', rate: 1.2 },
      { t: 8.0, type: 'autoTap', rate: 0 },
    ],
  },
  {
    name: 'Reverse & re-align',
    hint: 'DC on, settle, change polarity — the visual pattern twitches and re-forms.',
    duration: 14,
    params: { currentA: 40, currentMode: 'dc' },
    timeline: [
      { t: 0.2, type: 'sprinkle', count: 14000, strayCount: 3000, pattern: 'sheet', radius: 0.17, clump: 0.01 },
      { t: 1.5, type: 'current', on: true, amp: 40, mode: 'dc', rampDur: 0.4 },
      { t: 2.5, type: 'tapBurst', n: 4, interval: 0.5, strength: 8 },
      { t: 7.0, type: 'current', on: true, amp: -40, mode: 'dc', rampDur: 0.8 },
      { t: 8.5, type: 'tapBurst', n: 4, interval: 0.5, strength: 8 },
    ],
  },
  {
    name: 'Bare stage',
    hint: 'Empty timeline — drive everything live from the panel.',
    duration: 20,
    timeline: [],
  },
  {
    name: 'Surge stage 25→100 A',
    hint: 'Continuous-shot setup: 25 A, 10 rings, falloff 1.0, no sprinkle. Arrange the filings, roll camera, then hit ⚡ Surge to ramp amplitude to 100 A with 14 rings and falloff 0.85 plus a tap — all in one move.',
    duration: 24,
    ui: { currentOn: true, fieldLineCount: 10, fieldFalloffCurve: 1.0 },
    params: { currentA: 25, currentMode: 'dc', rampDur: 0.4 },
    timeline: [],
  },
];
