import { DEFAULT_UI } from './defaults.js';

// Preset takes. Each is { name, hint, duration, params?, timeline }.
// Timelines use the un-expanded event grammar from sim/timeline.js.

export const PRESETS = [
  {
    name: 'Manual stage',
    hint: 'Starts from the saved filming setup: current on, dense sprinkle, tap when you want the reveal.',
    duration: 20,
    ui: { ...DEFAULT_UI },
    cal: { holeWallR: 0.0115 },
    params: {
      currentA: 30,
      currentMode: 'dc',
      acFreq: 5,
      rampDur: 0.4,
      currentDir: 1,
      currentAutoAlign: false,
      currentMotion: 0.50,
      fieldReach30A: 0.080,
      fieldFalloffPower: 1.15,
      chainSpacing: 0.003,
      chainStrength: 0.30,
      inwardPull: 0.00325,
      visualFriction: 0.25,
      slideAmount: 1.00,
      alignSpeed: 4.0,
      rotateSpeed: 5.25,
      tapStrength: 8.0,
      tapLiftAll: 1.0,
      tapJitterAmount: 0.28,
      filingMedianL: 0.70e-3,
      sprinkleCount: 18000,
      strayCount: 2401,
      sprinkleR: 0.190,
      sprinklePattern: 'sheet',
      sprinkleClump: 0.65,
    },
    timeline: [
      { t: 0.2, type: 'sprinkle', count: 18000, strayCount: 2401, pattern: 'sheet', radius: 0.190, clump: 0.65 },
    ],
  },
  {
    name: 'Classic reveal',
    hint: 'Sprinkle → current on → taps → cheated field arcs bloom outward from the wire.',
    duration: 9,
    params: { currentA: 30, currentMode: 'dc' },
    timeline: [
      { t: 0.2, type: 'sprinkle', count: 14000, strayCount: 3000, pattern: 'sheet', radius: 0.17, clump: 0.01 },
      { t: 2.0, type: 'current', on: true, amp: 30, mode: 'dc', rampDur: 0.5 },
      { t: 3.0, type: 'tap', strength: 8 },
      { t: 3.6, type: 'tap', strength: 8 },
      { t: 4.2, type: 'tap', strength: 9 },
      { t: 5.0, type: 'tap', strength: 7 },
      { t: 5.8, type: 'tap', strength: 6 },
    ],
  },
  {
    name: 'High current bloom',
    hint: '80 A — the aligned region expands quickly after taps.',
    duration: 9,
    params: { currentA: 80, currentMode: 'dc' },
    timeline: [
      { t: 0.2, type: 'sprinkle', count: 15000, strayCount: 3000, pattern: 'sheet', radius: 0.18, clump: 0.01 },
      { t: 1.8, type: 'current', on: true, amp: 80, mode: 'dc', rampDur: 0.6 },
      { t: 2.8, type: 'tapBurst', n: 5, interval: 0.55, strength: 9 },
      { t: 6.2, type: 'tap', strength: 5 },
    ],
  },
  {
    name: 'Tap vs no tap',
    hint: 'Current on for 3 s — it waits. Then taps reveal the field.',
    duration: 12,
    params: { currentA: 30, currentMode: 'dc' },
    timeline: [
      { t: 0.2, type: 'sprinkle', count: 14000, strayCount: 3000, pattern: 'sheet', radius: 0.17, clump: 0.01 },
      { t: 1.5, type: 'current', on: true, amp: 30, mode: 'dc', rampDur: 0.4 },
      { t: 6.0, type: 'tapBurst', n: 6, interval: 0.6, strength: 8 },
    ],
  },
  {
    name: 'AC shimmer',
    hint: '8 Hz AC — filings near the wire shimmer without settling far away.',
    duration: 10,
    params: { currentA: 45, currentMode: 'ac', acFreq: 8 },
    timeline: [
      { t: 0.2, type: 'sprinkle', count: 14000, strayCount: 3000, pattern: 'sheet', radius: 0.17, clump: 0.01 },
      { t: 1.5, type: 'current', on: true, amp: 45, mode: 'ac', freq: 8, rampDur: 0.8 },
      { t: 3.0, type: 'autoTap', rate: 1.2 },
      { t: 8.0, type: 'autoTap', rate: 0 },
    ],
  },
  {
    name: 'Reverse & re-align',
    hint: 'DC on, settle, change polarity — the visual pattern twitches and re-forms.',
    duration: 14,
    params: { currentA: 40, currentMode: 'dc' },
    timeline: [
      { t: 0.2, type: 'sprinkle', count: 14000, strayCount: 3000, pattern: 'sheet', radius: 0.17, clump: 0.01 },
      { t: 1.5, type: 'current', on: true, amp: 40, mode: 'dc', rampDur: 0.4 },
      { t: 2.5, type: 'tapBurst', n: 4, interval: 0.5, strength: 8 },
      { t: 7.0, type: 'current', on: true, amp: -40, mode: 'dc', rampDur: 0.8 },
      { t: 8.5, type: 'tapBurst', n: 4, interval: 0.5, strength: 8 },
    ],
  },
  {
    name: 'Bare stage',
    hint: 'Empty timeline — drive everything live from the panel.',
    duration: 20,
    timeline: [],
  },
  {
    // Compass ring-trace take: CLEAR board — the story is the compass and
    // two wide field rings (220 px and ×1.90). Load (30 A up, both rings
    // showing, compass parked ON ring 1), roll camera, then press
    // '☉ Trace rings one by one': ring 2 hides, the compass makes a full
    // revolution riding ring 1 with its needle tangent to the field, ring 2
    // reappears as the compass glides out to it, and it traces that ring
    // the same way. compassX/Y precomputed on ring 1 (bearing 35°) for the
    // default calibration.
    name: 'Compass trace stage',
    hint: 'Clear board, 30 A, 2 wide rings, compass on ring 1. Press ☉ Trace rings one by one for the full choreography.',
    duration: 20,
    ui: {
      currentOn: true,
      fieldLineCount: 2,
      fieldFirstRadiusPx: 220,
      fieldRadiusMultiplier: 1.90,
      fieldMaxRadiusPx: 1420,
      fieldFalloffCurve: 1.0,
      fieldLineStrength: 3.0,
      fieldLineOpacity: 0.32,
      fieldLineThickness: 2.20,
      fieldLineDetail: 88,
      fieldMotionSpeed: 1.0,
      fieldMotionThickness: 0.75,
      currentIndicatorStrength: 0.60,
      currentPulseSpeed: 1.0,
      boardShake: 0.90,
      showCompass: true,
      compassSize: 0.036,
      compassSensitivity: 3.0,
      compassOrbitDur: 7,
      compassX: 0.2428,
      compassY: 0.1916,
    },
    params: {
      currentA: 30,
      currentMode: 'dc',
      acFreq: 5,
      rampDur: 0.4,
      currentDir: 1,
      currentMotion: 0.50,
      fieldReach30A: 0.080,
      fieldFalloffPower: 1.15,
      chainSpacing: 0.0030,
      chainStrength: 0.30,
      inwardPull: 0.00325,
      pullRadius: 0.045,
      axisPull: 0.0012,
      visualFriction: 0.25,
      slideAmount: 1.0,
      alignSpeed: 4.0,
      rotateSpeed: 5.25,
      tapStrength: 8.0,
      tapLiftAll: 1.0,
      tapJitterAmount: 0.28,
      filingMedianL: 0.70e-3,
      sprinkleCount: 18000,
      strayCount: 2401,
      sprinkleR: 0.190,
      sprinklePattern: 'sheet',
      sprinkleClump: 0.65,
    },
    timeline: [],   // clear board — the compass and the rings tell the story
  },
  {
    // Continuous-shot surge take: the timeline sprinkles the whole board
    // and settles it with THREE taps at the 25 A base look. Roll camera,
    // then hit ⚡ Surge: amplitude ramps to 100 A, pulses brighten to 0.9×
    // and speed to 2.5×, the filing response strengthens (chain 1.85×,
    // inward pull 7.25 mm, pull radius 140 mm, middle-line 5.75 mm) and
    // ONE tap blooms the pattern — the rings themselves stay put.
    name: 'Surge stage 25→100 A',
    hint: 'Sprinkles + 3 settle taps at 25 A. Roll camera, then ⚡ Surge: 100 A, pulses 2.5×, response strengthens, ONE tap.',
    duration: 24,
    ui: {
      currentOn: true,
      fieldLineCount: 10,
      fieldFalloffCurve: 0.85,
      fieldRadiusMultiplier: 1.47,
      fieldFirstRadiusPx: 59,
      fieldMaxRadiusPx: 1450,
      fieldLineStrength: 3.0,
      fieldLineOpacity: 0.32,
      fieldLineThickness: 2.20,
      fieldLineDetail: 88,
      fieldMotionSpeed: 1.0,
      fieldMotionThickness: 0.75,
      currentIndicatorStrength: 0.60,
      currentPulseSpeed: 1.0,
      boardShake: 0.90,
      showCompass: true,
      compassSize: 0.056,
      compassSensitivity: 3.0,
      compassOrbitDur: 8,
    },
    params: {
      currentA: 25,
      currentMode: 'dc',
      acFreq: 5,
      rampDur: 0.4,
      currentDir: 1,
      currentMotion: 0.55,
      fieldReach30A: 0.340,
      fieldFalloffPower: 1.15,
      chainSpacing: 0.0030,
      chainStrength: 1.0,
      inwardPull: 0.00425,
      pullRadius: 0.085,
      axisPull: 0.00325,
      visualFriction: 0.25,
      slideAmount: 1.0,
      alignSpeed: 4.0,
      rotateSpeed: 5.25,
      tapStrength: 8.0,
      tapLiftAll: 0.0,
      tapJitterAmount: 0.28,
      filingMedianL: 0.70e-3,
      sprinkleCount: 18000,
      strayCount: 2401,
      sprinkleR: 0.190,
      sprinklePattern: 'sheet',
      sprinkleClump: 0.65,
    },
    timeline: [
      { t: 0.2, type: 'sprinkle', count: 18000, strayCount: 2401, pattern: 'sheet', radius: 0.190, clump: 0.65 },
      { t: 1.2, type: 'tapBurst', n: 3, interval: 0.55, strength: 8 },
    ],
  },
];
